[project]
name = ""
version = ""
description = ""
authors = [
    {name = "bar", email = "foo@bar.com"},
]
dependencies = [
    "gradio",
    "pandas",
    "pipetools",
    "loguru>=0.7.2",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

